# Generated by Django 3.2.25 on 2024-05-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=50)),
                ('char_race', models.CharField(max_length=30)),
                ('char_class', models.CharField(max_length=30)),
                ('char_lvl', models.PositiveIntegerField()),
                ('background', models.CharField(max_length=30)),
                ('alignment', models.CharField(max_length=30)),
                ('char_str', models.IntegerField()),
                ('char_dex', models.IntegerField()),
                ('char_con', models.IntegerField()),
                ('char_int', models.IntegerField()),
                ('char_wis', models.IntegerField()),
                ('char_char', models.IntegerField()),
            ],
        ),
    ]
