# Generated by Django 3.2.25 on 2024-05-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheet', '0002_auto_20240506_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.AddField(
            model_name='character',
            name='Charisma',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Constitution',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Dexterity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='Wisdom',
            field=models.IntegerField(null=True),
        ),
    ]
